FindYourItem/FindYourItem/Controllers/AdminResgistrationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FindYourItem.Models;

namespace FindYourItem.Controllers
{
    public class AdminResgistrationController : Controller
    {

        private ApplicationDbContext _context;

        public AdminResgistrationController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }




        // GET: AdminResgistration
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Save(AdminDetail adminDetail)
        {
            if (!ModelState.IsValid)
            {
                return View("Index");
            }

            if (_context.AdminDetails.Any(x => x.StoreId == adminDetail.StoreId))
            {
                ViewBag.DuplicateMessage = "Store ID Already exists";
                return View("Index");
            }

            if (adminDetail.Id == 0)
                _context.AdminDetails.Add(adminDetail);

            else
            {
                var adminDetailInDb = _context.AdminDetails.Single(p => p.Id == adminDetail.Id);
                adminDetailInDb.Location = adminDetail.Location;
                adminDetailInDb.Password = adminDetail.Password;
                adminDetailInDb.StoreId = adminDetail.StoreId;
                adminDetailInDb.Username = adminDetail.Username;
                adminDetailInDb.AdminName = adminDetail.AdminName;
                adminDetailInDb.EmailAddress = adminDetail.EmailAddress;

            }
                _context.SaveChanges();
           
            
            return Content("Congratulations");
            
        }



    }
}

FindYourItem/FindYourItem/Controllers/Api/AdminResgistrationController.cs
using FindYourItem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;
using AutoMapper;
using FindYourItem.Dtos;

namespace FindYourItem.Controllers.Api
{
    public class AdminResgistrationController : ApiController
    {
        private ApplicationDbContext _context;

        public AdminResgistrationController()
        {
            _context = new ApplicationDbContext();
        }



        [System.Web.Http.HttpGet]
        [EnableCors(origins: "http://localhost:4200", headers: "*", methods: "*")]
        // GET api/adminresgistration
        //public IHttpActionResult LoginAdmin(AdminDetailDto adminDetailsDto)
        public IHttpActionResult GetProductsByAdmin(AdminDetailDto adminDetailsDto)
        {

            if (_context.AdminDetails.Any(x => x.Username == adminDetailsDto.Username))
            {
                var admin = _context.AdminDetails.Select(selector: Mapper.Map<AdminDetail, AdminDetailDto>).Where(x => x.Username == adminDetailsDto.Username).SingleOrDefault();

                var prodcuts = _context.ProductDetails.Where(product => admin.Id == product.AdminDetail.Id).ToList();

                return Ok(prodcuts);
            }



            return NotFound();
            //else
            //{
            //    return Ok("Chl Cutiyeeeee");

            //}

        }




        [System.Web.Http.HttpGet]
        [EnableCors(origins: "http://localhost:4200", headers: "*", methods: "*")]
        public IHttpActionResult loginAdmin(string userName, string password)
        {
            var admin = _context.AdminDetails.Select(selector: Mapper.Map<AdminDetail, AdminDetailDto>).Where(x => x.Username == userName && x.Password == password);

            if (!admin.Any()) return NotFound();

            return Ok(admin.First());
        }





        [System.Web.Http.HttpPost]
        [EnableCors(origins: "http://localhost:4200", headers: "*", methods: "*")]

        public IHttpActionResult CreateAdminDetail(AdminDetailDto adminDetailsDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            if (_context.AdminDetails.Any(x => x.StoreId == adminDetailsDto.StoreId))
            {
                return Ok("Store Id already exists.");
            }
            var adminDetails = Mapper.Map<AdminDetailDto, AdminDetail>(adminDetailsDto);

                _context.AdminDetails.Add(adminDetails);
                _context.SaveChanges();
               
               adminDetailsDto.Id = adminDetails.Id;
               return Created(new Uri(Request.RequestUri + "/" + adminDetails.Id), adminDetailsDto);
        }
    }
}

FindYourItem/FindYourItem/Views/AdminResgistration/Index.cshtml
@model FindYourItem.Models.AdminDetail
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("Save", "AdminResgistration"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.StoreId)
        @Html.TextBoxFor(m => m.StoreId, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.StoreId)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.AdminName)
        @Html.TextBoxFor(m => m.AdminName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AdminName)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Username)
        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Username)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Password)
        @Html.TextBoxFor(m => m.Password, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Password)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EmailAddress)
        @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.EmailAddress)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Location)
        @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Location)
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-danger">@ViewBag.DuplicateMessage</label>
    
        </div>
    </div>
    @*@Html.HiddenFor(m => m.Id)*@

    <button type="submit" class="btn btn-primary">Save</button>
}